sudo: required
dist: trusty

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - vim-gtk
      - silversearcher-ag

before_script:
  - if [[ "$TRAVIS_OS_NAME" == osx ]]; then brew update && brew install vim the_silver_searcher; fi

script:
  - test/run
