language: vim

before_script: |
  git clone https://github.com/junegunn/vader.vim.git
  git clone https://github.com/tpope/vim-repeat

script: |
  vim -Nu <(cat << VIMRC
  filetype off
  set rtp+=vader.vim
  set rtp+=vim-repeat
  set rtp+=.
  filetype plugin indent on
  syntax enable
  VIMRC) -c 'Vader! test/*' > /dev/null
