#!/bin/bash

##############################################################################
# **NOTE** This file lives in both ~/bin and ~/.vim/tool.
##############################################################################

FIFO=${1:-.fifo}
trap 'rm "${FIFO}"' 0
mkfifo "${FIFO}" || exit 1
read -r _junk < "${FIFO}"
